Misha/ob-122_collatz_conjecture
glock3/Learning- pull request #28
Opened 2020-09-23 19:19 UTC by krassovki

2020-09-23 20:15 UTC, glock3 requested changes

2020-09-23 20:15 UTC, glock3 commented on Misha/OB-122_collatz_conjecture/collatz_conjecture.py
> +        pass
Why do you need this? What does it do?

2020-09-23 20:15 UTC, glock3 commented on Misha/OB-122_collatz_conjecture/collatz_conjecture_test.py
> +class CollatzConjectureTest(unittest.TestCase):
Please add test cases with valid data and border values

2020-09-23 20:15 UTC, glock3 commented on Misha/OB-122_collatz_conjecture/collatz_conjecture.py
> +    def wrapper_with_arguments(arg1):
Naming
Do you have arg2?

2020-09-24 16:20 UTC, krassovki commented on Misha/OB-122_collatz_conjecture/collatz_conjecture.py
> +        pass
already deleted this

2020-09-24 16:20 UTC, krassovki commented on Misha/OB-122_collatz_conjecture/collatz_conjecture.py
> +    def wrapper_with_arguments(arg1):
corrected

2020-09-24 16:23 UTC, krassovki commented on Misha/OB-122_collatz_conjecture/collatz_conjecture_test.py
> +class CollatzConjectureTest(unittest.TestCase):
two right values were added before your rewiev - 7 and 12. test_cc_with_right_value_2 and test_cc_with_right_value

2020-09-29 18:16 UTC, glock3 approved these changes

2020-09-29 18:16 UTC, glock3 commented on Misha/OB-122_collatz_conjecture/collatz_conjecture.py
> +import time
Move tasks to Algorithm folder

2020-09-29 18:16 UTC, merged