add collatz conjecture with tests
glock3/Learning- pull request #35
Opened 2020-09-25 17:59 UTC by Horus1223

2020-09-25 18:14 UTC, Horus1223 commented
add collatz_conjecture and tests

2020-09-29 21:04 UTC, glock3 requested changes

2020-09-29 21:04 UTC, glock3 commented on Dima/Classic_Algorithms/collatz_conjecture/collatz_conjecture.py
> +        ValueError('ValueError')
Please take a look on comments for other tasks regarding exceptions
Change messages to ValueError_1 and ValuerError_2 + tests

2020-09-30 17:13 UTC, glock3 approved these changes

2020-09-30 17:14 UTC, merged